In [1]:
import torch
import torch.nn as nn

In [3]:
loss = nn.CrossEntropyLoss()
print(f"loss : {loss},  type of loss : {type(loss)}")

loss : CrossEntropyLoss(),  type of loss : <class 'torch.nn.modules.loss.CrossEntropyLoss'>


In [31]:
torch.manual_seed(111)
input = torch.randn(3, 5, requires_grad=True)
print(f"input :\n{input}")
print()

target = torch.empty(3, dtype=torch.long).random_(5)
print(f"target :\n{target}")

input :
tensor([[-0.1222, -0.7573,  1.0416,  0.3303,  0.5315],
        [-1.0235,  1.3560,  0.3086,  0.5228, -1.0928],
        [ 1.9796, -0.2610, -0.1857,  0.8947, -0.5097]], requires_grad=True)

target :
tensor([0, 2, 4])


In [34]:
output = loss(input, target)
print(output)

tensor(2.2718, grad_fn=<NllLossBackward>)


In [35]:
output.backward()

In [36]:
loss(input, target)

tensor(2.2718, grad_fn=<NllLossBackward>)

In [38]:
torch.manual_seed(111)
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
print(f"input :\n{input}")
print()
target = torch.randn(3,5).softmax(dim=1)
print(f"target :\n{target}")
print()
output = loss(input, target)
print(f"output : {output}")
output.backward()

input :
tensor([[-0.1222, -0.7573,  1.0416,  0.3303,  0.5315],
        [-1.0235,  1.3560,  0.3086,  0.5228, -1.0928],
        [ 1.9796, -0.2610, -0.1857,  0.8947, -0.5097]], requires_grad=True)

target :
tensor([[0.5297, 0.2047, 0.0511, 0.0235, 0.1910],
        [0.4833, 0.2020, 0.0526, 0.1142, 0.1479],
        [0.3178, 0.1287, 0.0485, 0.3405, 0.1645]])
