In [1]:
import torch
import torch.nn as nn

In [58]:
logits = torch.tensor([[1.2, 0.5, -0.8], [-0.5, 0.8, 2.0]], requires_grad=True)
labels = torch.tensor([0, 2])

cross_entropy_loss = nn.CrossEntropyLoss()
loss = cross_entropy_loss(logits, labels)
print(loss)
loss.backward()

import numpy as np
sum0 = sum(np.exp(x) for x in [1.2, 0.5, -0.8])
sum1 = sum(np.exp(x) for x in [-0.5, 0.8, 2.0])

p0 = np.exp(1.2)/sum0
p1 = np.exp(2.0)/sum1

my_loss = -(np.log(p0) + np.log(p1)) / 2
print(my_loss)

tensor(0.4071, grad_fn=<NllLossBackward>)
0.4071072576720597


In [53]:
np.log(1,2)

TypeError: return arrays must be of ArrayType

In [67]:
target = torch.tensor( 1 )
target.item(), target.shape

(1, torch.Size([]))

In [66]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data[1][1].item()

4

In [2]:
import torch
labels = torch.randn(1, 5)
print(labels)

tensor([[-0.6014,  0.3614, -0.1621, -0.5402, -1.0111]])


In [27]:
import torch
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
print(f"a : {a}\nb : {b}")

Q = 3 * a ** 3 - b ** 2
print(f"Q : {Q}")

# 현재 Q는 scalar값이 아닌 vector이므로 .backward()의 gradient인자에 자기자신에 대한 gradient인 1을 명시해야 한다.
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

print(f"a.grad : {a.grad}\nb.grad : {b.grad}")
print(a.grad == 9 * a ** 2)
print(b.grad == -2 * b)

a : tensor([2., 3.], requires_grad=True)
b : tensor([6., 4.], requires_grad=True)
Q : tensor([-12.,  65.], grad_fn=<SubBackward0>)
a.grad : tensor([36., 81.])
b.grad : tensor([-12.,  -8.])
tensor([True, True])
tensor([True, True])


RuntimeError: Trying to backward through the graph a second time (or directly access saved variables after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved variables after calling backward.

In [6]:
Q.backward()

RuntimeError: grad can be implicitly created only for scalar outputs