In [23]:
import torch
from torchvision.models import resnet18

In [24]:
model = resnet18(pretrained=True)

In [42]:
torch.manual_seed(2024)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)
print(f"data shape : {data.shape},  labels shape : {labels.shape}")

data shape : torch.Size([1, 3, 64, 64]),  labels shape : torch.Size([1, 1000])


In [34]:
print(f"The first 3 rows of data :\n{data[0][:]}")

The first 3 rows of data :
tensor([[[0.5317, 0.8313, 0.9718, 0.1193],
         [0.1669, 0.3495, 0.2150, 0.6201],
         [0.4849, 0.7492, 0.1521, 0.5625],
         [0.1735, 0.7046, 0.9265, 0.4061],
         [0.3045, 0.9073, 0.7637, 0.6101]],

        [[0.8914, 0.9090, 0.6652, 0.6786],
         [0.2268, 0.5031, 0.2151, 0.7988],
         [0.0784, 0.0706, 0.2972, 0.0692],
         [0.9827, 0.6969, 0.6907, 0.4406],
         [0.5646, 0.1914, 0.3562, 0.5626]],

        [[0.0469, 0.4520, 0.4588, 0.7574],
         [0.9929, 0.5146, 0.4524, 0.9701],
         [0.2343, 0.6591, 0.6730, 0.1999],
         [0.2684, 0.5766, 0.2735, 0.4980],
         [0.9732, 0.4558, 0.7026, 0.8392]]])


In [41]:
data[0][:][:][:][:2]

tensor([[[0.5317, 0.8313, 0.9718, 0.1193],
         [0.1669, 0.3495, 0.2150, 0.6201],
         [0.4849, 0.7492, 0.1521, 0.5625],
         [0.1735, 0.7046, 0.9265, 0.4061],
         [0.3045, 0.9073, 0.7637, 0.6101]],

        [[0.8914, 0.9090, 0.6652, 0.6786],
         [0.2268, 0.5031, 0.2151, 0.7988],
         [0.0784, 0.0706, 0.2972, 0.0692],
         [0.9827, 0.6969, 0.6907, 0.4406],
         [0.5646, 0.1914, 0.3562, 0.5626]]])

In [22]:
print(f"The first 3 values of labels :\n{labels[0][:3]}")

The first 3 values of labels :
tensor([0.3281, 0.4538, 0.5450])


In [14]:
predictions = model(data)
print(f"prediction shape : {predictions.shape}")

prediction shape : torch.Size([1, 1000])


C:\Users\rubin\anaconda3\envs\torch_book\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
