In [23]:
import torch
from torchvision.models import resnet18

In [24]:
model = resnet18(pretrained=True)

In [42]:
torch.manual_seed(2024)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)
print(f"data shape : {data.shape},  labels shape : {labels.shape}")

data shape : torch.Size([1, 3, 64, 64]),  labels shape : torch.Size([1, 1000])


In [43]:
print(f"data :\n{data}")

data :
tensor([[[[0.5317, 0.8313, 0.9718,  ..., 0.4847, 0.5086, 0.0755],
          [0.1806, 0.8887, 0.0568,  ..., 0.7124, 0.3392, 0.8287],
          [0.1990, 0.7496, 0.7408,  ..., 0.4832, 0.1860, 0.7967],
          ...,
          [0.9950, 0.4322, 0.4230,  ..., 0.5241, 0.6104, 0.2882],
          [0.3538, 0.3196, 0.9105,  ..., 0.7177, 0.8401, 0.1001],
          [0.1443, 0.7446, 0.2227,  ..., 0.8566, 0.7337, 0.5822]],

         [[0.3231, 0.7837, 0.2890,  ..., 0.0890, 0.5950, 0.0524],
          [0.2924, 0.9103, 0.9647,  ..., 0.0363, 0.8849, 0.8601],
          [0.5322, 0.9166, 0.0131,  ..., 0.5262, 0.4500, 0.9072],
          ...,
          [0.1001, 0.5510, 0.0747,  ..., 0.2623, 0.7240, 0.5774],
          [0.5152, 0.2218, 0.3293,  ..., 0.9807, 0.7555, 0.0507],
          [0.8055, 0.1036, 0.4741,  ..., 0.5605, 0.9798, 0.2815]],

         [[0.8189, 0.3113, 0.5315,  ..., 0.1022, 0.0160, 0.1067],
          [0.4933, 0.4094, 0.9481,  ..., 0.1944, 0.9233, 0.8198],
          [0.3355, 0.2035, 0.6832, 

In [45]:
print(f"labels :\n{labels}")

labels :
tensor([[0.3281, 0.4538, 0.5450, 0.5768, 0.2181, 0.2331, 0.1799, 0.7429, 0.2024,
         0.2068, 0.3798, 0.8641, 0.9683, 0.4784, 0.4658, 0.7490, 0.4124, 0.3615,
         0.3245, 0.0080, 0.9187, 0.1001, 0.3092, 0.1171, 0.9075, 0.2663, 0.3020,
         0.6438, 0.6232, 0.2813, 0.3420, 0.8625, 0.5421, 0.2025, 0.9147, 0.3137,
         0.3417, 0.4132, 0.3255, 0.6492, 0.3737, 0.3964, 0.0915, 0.6050, 0.4437,
         0.5992, 0.8061, 0.3848, 0.0820, 0.2925, 0.3543, 0.2385, 0.5150, 0.1673,
         0.7653, 0.3498, 0.5024, 0.5848, 0.3841, 0.3126, 0.6877, 0.0547, 0.8015,
         0.0398, 0.1905, 0.5825, 0.3592, 0.6434, 0.8421, 0.5067, 0.5713, 0.7298,
         0.4879, 0.0013, 0.4169, 0.4990, 0.7923, 0.9207, 0.7458, 0.7006, 0.4115,
         0.7747, 0.9162, 0.4701, 0.1278, 0.7333, 0.1305, 0.6698, 0.4929, 0.9677,
         0.9850, 0.1028, 0.3573, 0.1225, 0.3832, 0.7065, 0.1470, 0.5021, 0.4542,
         0.1700, 0.0444, 0.1825, 0.5943, 0.3744, 0.7116, 0.2241, 0.7884, 0.9705,
         0.2900, 0.

In [14]:
predictions = model(data)
print(f"prediction shape : {predictions.shape}")

prediction shape : torch.Size([1, 1000])


C:\Users\rubin\anaconda3\envs\torch_book\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)


In [46]:
print(predictions)

tensor([[-3.7863e-01, -4.2551e-01, -6.4376e-01, -1.6006e+00, -7.1355e-01,
         -4.3830e-01, -6.5101e-01,  5.1927e-01,  2.7013e-01, -5.9241e-01,
         -9.2290e-01, -8.2714e-01, -2.5428e-01, -9.5382e-01, -1.0358e+00,
         -4.8358e-01, -1.0214e+00, -3.7489e-01, -4.9071e-01, -6.6538e-01,
         -1.5787e+00, -7.4878e-01, -1.4900e+00,  2.6773e-01, -8.5796e-01,
         -1.3857e+00, -1.0709e+00, -1.5751e+00, -1.1230e+00, -6.6824e-01,
         -8.5564e-01, -9.9458e-01, -6.0063e-01, -4.6899e-01, -2.0058e-01,
         -3.0349e-01,  5.7332e-01, -5.3821e-01, -5.8122e-01, -4.7847e-02,
         -7.9053e-01, -9.0189e-01, -1.1881e+00, -3.3052e-01, -7.2539e-01,
         -4.4485e-01, -8.5603e-01, -4.7950e-01, -1.3098e+00, -8.9900e-01,
         -3.5040e-01,  3.3551e-01, -3.6762e-01, -6.0958e-01, -1.4892e-01,
         -9.6768e-01, -3.6088e-01, -1.3634e+00, -4.2371e-01, -4.2097e-01,
          7.5787e-01,  1.5216e-02,  2.6455e-02,  2.2891e-02, -6.3366e-01,
         -3.5739e-01, -4.5912e-01, -8.

In [49]:
loss = (predictions - labels).sum()
print(loss)
print(loss.shape)

tensor(-484.5069, grad_fn=<SumBackward0>)
torch.Size([])


In [50]:
loss.backward()

In [51]:
optimizer = torch.optim.SGD(params=model.parameters(), lr=0.01, momentum=0.9)